var MongoClient = require('mongodb').MongoClient;

var URL = "mongodb+srv://root:root@kuriuscluster.md9cifv.mongodb.net/?retryWrites=true&w=majority";
var DB_NAME = 'kuiriusdb'


var cities = [
    {name: "Porto", featured: true},
    {name: "Matosinhos", featured: true},
    {name: "Vila Nova de Gaia", featured: true},
    {name: "Lisboa", featured: true},
    {name: "Oeiras", featured: true},
    {name: "Cascais", featured: true},
    {name: "Sintra", featured: true},
    {name: "Loures", featured: true},
    {name: "Braga", featured: true},
    {name: "Almada", featured: true},
    {name: "Vila Real", featured: true}, 
    {name: "Viana do Castelo", featured: true},
    {name: "Amarante", featured: true},
    {name: "Guimarães", featured: true},
    {name: "Chaves", featured: true},
    {name: "Mirandela", featured: true},
    {name: "Bragança", featured: true},
    {name: "Setúbal", featured: true},
    {name: "Évora", featured: true},
    {name: "Figueira da Foz", featured: true},
    {name: "Beja", featured: true},
    {name: "Albufeira", featured: true},
    {name: "Lagos", featured: true},
    {name: "Faro", featured: true},
    {name: "Portimão", featured: true},
    {name: "Fátima", featured: true},
    {name: "Leiria", featured: true},
    {name: "Coimbra", featured: true},
    {name: "Castelo Branco", featured: true},
    {name: "Guarda", featured: true},
    {name: "Viseu", featured: true},
    {name: "Lamego", featured: true}, 
    {name: "Covilhã", featured: true}, 
    {name: "Bairrada", featured: true},
    {name: "Aveiro", featured: true},
    {name: "Abrantes", featured: false},
    {name: "Agualva-Cacém", featured: false},
    {name: "Águeda", featured: false},
    {name: "Albergaria-a-Velha", featured: false},
    {name: "Alcácer do Sal", featured: false},
    {name: "Alcobaça", featured: false},
    {name: "Alfena", featured: false},
    {name: "Almeirim", featured: false},
    {name: "Alverca do Ribatejo", featured: false},
    {name: "Amadora", featured: false},
    {name: "Amora", featured: false},
    {name: "Anadia", featured: false},
    {name: "Angra do Heroísmo", featured: false},
    {name: "Barcelos", featured: false},
    {name: "Barreiro", featured: false},
    {name: "Beja", featured: false},
    {name: "Borba", featured: false},
    {name: "Caldas da Rainha", featured: false},
    {name: "Câmara de Lobos", featured: false},
    {name: "Caniço", featured: false},
    {name: "Cantanhede", featured: false},
    {name: "Cartaxo", featured: false},
    {name: "Costa da Caparica", featured: false},
    {name: "Covilhã", featured: false},
    {name: "Elvas", featured: false},
    {name: "Entroncamento", featured: false},
    {name: "Ermesinde", featured: false},
    {name: "Esmoriz", featured: false},
    {name: "Espinho", featured: false},
    {name: "Esposende", featured: false},
    {name: "Estarreja", featured: false},
    {name: "Estremoz", featured: false},
    {name: "Fafe", featured: false},
    {name: "Felgueiras", featured: false},
    {name: "Fiães", featured: false},
    {name: "Freamunde", featured: false},
    {name: "Funchal", featured: false},
    {name: "Fundão", featured: false},
    {name: "Gafanha da Nazaré", featured: false},
    {name: "Gandra", featured: false},
    {name: "Gondomar", featured: false},
    {name: "Gouveia", featured: false},
    {name: "Horta", featured: false},
    {name: "Ílhavo", featured: false},
    {name: "Lagoa (Açores)", featured: false},
    {name: "Lagoa", featured: false},
    {name: "Lagos", featured: false},
    {name: "Lamego", featured: false},
    {name: "Leiria", featured: false},
    {name: "Lixa", featured: false},
    {name: "Lordelo (Paredes)", featured: false},
    {name: "Loulé", featured: false},
    {name: "Loures", featured: false},
    {name: "Lourosa", featured: false},
    {name: "Macedo de Cavaleiros", featured: false},
    {name: "Machico", featured: false},
    {name: "Maia", featured: false},
    {name: "Mangualde", featured: false},
    {name: "Marco de Canaveses", featured: false},
    {name: "Marinha Grande", featured: false},
    {name: "Mealhada", featured: false},
    {name: "Mêda", featured: false},
    {name: "Miranda do Douro", featured: false},
    {name: "Montemor-o-Novo", featured: false},
    {name: "Montijo", featured: false},
    {name: "Moura", featured: false},
    {name: "Odivelas", featured: false},
    {name: "Olhão", featured: false},
    {name: "Oliveira de Azeméis", featured: false},
    {name: "Oliveira do Bairro", featured: false},
    {name: "Oliveira do Hospital", featured: false},
    {name: "Ourém", featured: false},
    {name: "Ovar", featured: false},
    {name: "Paços de Ferreira", featured: false},
    {name: "Paredes", featured: false},
    {name: "Penafiel", featured: false},
    {name: "Peniche", featured: false},
    {name: "Peso da Régua", featured: false},
    {name: "Pinhel", featured: false},
    {name: "Pombal", featured: false},
    {name: "Ponta Delgada", featured: false},
    {name: "Ponte de Sor", featured: false},
    {name: "Portalegre", featured: false},
    {name: "Póvoa de Santa Iria", featured: false},
    {name: "Póvoa de Varzim", featured: false},
    {name: "Praia da Vitória", featured: false},
    {name: "Quarteira", featured: false},
    {name: "Queluz", featured: false},
    {name: "Rebordosa", featured: false},
    {name: "Reguengos de Monsaraz", featured: false},
    {name: "Ribeira Grande", featured: false},
    {name: "Rio Maior", featured: false},
    {name: "Rio Tinto", featured: false},
    {name: "Sabugal", featured: false},
    {name: "Sacavém", featured: false},
    {name: "Samora Correia", featured: false},
    {name: "Santa Comba Dão", featured: false},
    {name: "Santa Cruz", featured: false},
    {name: "Santa Maria da Feira", featured: false},
    {name: "Santana", featured: false},
    {name: "Santarém", featured: false},
    {name: "Santiago do Cacém", featured: false},
    {name: "Santo Tirso", featured: false},
    {name: "São João da Madeira", featured: false},
    {name: "São Mamede de Infesta", featured: false},
    {name: "São Pedro do Sul", featured: false},
    {name: "Seia", featured: false},
    {name: "Seixal", featured: false},
    {name: "Senhora da Hora", featured: false},
    {name: "Serpa", featured: false},
    {name: "Silves", featured: false},
    {name: "Sines", featured: false},
    {name: "Tarouca", featured: false},
    {name: "Tavira", featured: false},
    {name: "Tomar", featured: false},
    {name: "Tondela", featured: false},
    {name: "Torres Novas", featured: false},
    {name: "Torres Vedras", featured: false},
    {name: "Trancoso", featured: false},
    {name: "Trofa", featured: false},
    {name: "Valbom", featured: false},
    {name: "Vale de Cambra", featured: false},
    {name: "Valença", featured: false},
    {name: "Valongo", featured: false},
    {name: "Valpaços", featured: false},
    {name: "Vendas Novas", featured: false},
    {name: "Vila Baleira", featured: false},
    {name: "Vila do Conde", featured: false},
    {name: "Vila Franca de Xira", featured: false},
    {name: "Vila Nova de Famalicão", featured: false},
    {name: "Vila Nova de Foz Côa", featured: false},
    {name: "Vila Nova de Santo André", featured: false},
    {name: "Vila Real", featured: false},
    {name: "Vila Real de Santo António", featured: false},
    {name: "Vizela", featured: false},
    {name: "A dos Cunhados", featured: false},
    {name: "A dos Francos", featured: false},
    {name: "A Ver-o-Mar", featured: false},
    {name: "Abragão", featured: false},
    {name: "Abraveses", featured: false},
    {name: "Água de Pau", featured: false},
    {name: "Aguada de Cima (Águeda)", featured: false},
    {name: "Águas Santas", featured: false},
    {name: "Aguçadoura", featured: false},
    {name: "Aguiar da Beira", featured: false},
    {name: "Alcains", featured: false},
    {name: "Alcanena", featured: false},
    {name: "Alcanhões", featured: false},
    {name: "Alcantarilha", featured: false},
    {name: "Alcobertas", featured: false},
    {name: "Alcochete", featured: false},
    {name: "Alcoutim", featured: false},
    {name: "Alenquer", featured: false},
    {name: "Alfândega da Fé", featured: false},
    {name: "Alfarelos", featured: false},
    {name: "Alfeizerão", featured: false},
    {name: "Algés", featured: false},
    {name: "Algoz", featured: false},
    {name: "Algueirão - Mem Martins", featured: false},
    {name: "Alhadas", featured: false},
    {name: "Alhandra", featured: false},
    {name: "Alhos Vedros", featured: false},
    {name: "Alijó", featured: false},
    {name: "Aljezur", featured: false},
    {name: "Aljubarrota", featured: false},
    {name: "Aljustrel", featured: false},
    {name: "Almancil", featured: false},
    {name: "Almeida", featured: false},
    {name: "Almendra", featured: false},
    {name: "Almodôvar", featured: false},
    {name: "Alpiarça", featured: false},
    {name: "Alter do Chão", featured: false},
    {name: "Alvaiázere", featured: false},
    {name: "Alvalade", featured: false},
    {name: "Alvarães", featured: false},
    {name: "Alvite", featured: false},
    {name: "Alvito", featured: false},
    {name: "Alvor", featured: false},
    {name: "Amareleja", featured: false},
    {name: "Amares", featured: false},
    {name: "Amiais de Baixo", featured: false},
    {name: "Ançã", featured: false},
    {name: "Ancede", featured: false},
    {name: "Angeja", featured: false},
    {name: "Ansião", featured: false},
    {name: "Anta", featured: false},
    {name: "Apúlia", featured: false},
    {name: "Arazede", featured: false},
    {name: "Arco de Baúlhe", featured: false},
    {name: "Arcos de Valdevez", featured: false},
    {name: "Arcozelo (Ponte de Lima)", featured: false},
    {name: "Arcozelo (Vila Nova de Gaia)", featured: false},
    {name: "Arganil", featured: false},
    {name: "Argoncilhe", featured: false},
    {name: "Argozelo", featured: false},
    {name: "Armação de Pêra", featured: false},
    {name: "Armamar", featured: false},
    {name: "Arouca", featured: false},
    {name: "Arraiolos", featured: false},
    {name: "Arranhó", featured: false},
    {name: "Arrifana", featured: false},
    {name: "Arronches", featured: false},
    {name: "Arruda dos Vinhos", featured: false},
    {name: "Avanca", featured: false},
    {name: "Aveiras de Cima", featured: false},
    {name: "Avelar", featured: false},
    {name: "Avintes", featured: false},
    {name: "Avis", featured: false},
    {name: "Avô", featured: false},
    {name: "Azambuja", featured: false},
    {name: "Azueira", featured: false},
    {name: "Baião", featured: false},
    {name: "Baixa da Banheira", featured: false},
    {name: "Baltar", featured: false},
    {name: "Barrancos", featured: false},
    {name: "Barrosas", featured: false},
    {name: "Barroselas", featured: false},
    {name: "Batalha", featured: false},
    {name: "Belas", featured: false},
    {name: "Belmonte", featured: false},
    {name: "Benavente", featured: false},
    {name: "Benedita", featured: false},
    {name: "Benfica do Ribatejo", featured: false},
    {name: "Bensafrim", featured: false},
    {name: "Beringel", featured: false},
    {name: "Bobadela", featured: false},
    {name: "Boidobra", featured: false},
    {name: "Bombarral", featured: false},
    {name: "Bouro de Santa Maria", featured: false},
    {name: "Boticas", featured: false},
    {name: "Branca", featured: false},
    {name: "Britiande", featured: false},
    {name: "Brito", featured: false},
    {name: "Bucelas", featured: false},
    {name: "Bustos", featured: false},
    {name: "Cabanas de Tavira", featured: false},
    {name: "Cabanas de Viriato", featured: false},
    {name: "Cabeceiras de Basto", featured: false},
    {name: "Cacia", featured: false},
    {name: "Cadaval", featured: false},
    {name: "Caldas das Taipas", featured: false},
    {name: "Caldas de São Jorge", featured: false},
    {name: "Caldelas", featured: false},
    {name: "Calheta (Açores)", featured: false},
    {name: "Calheta (Madeira)", featured: false},
    {name: "Camacha", featured: false},
    {name: "Camarate", featured: false},
    {name: "Cambres", featured: false},
    {name: "Caminha", featured: false},
    {name: "Campelos", featured: false},
    {name: "Campo", featured: false},
    {name: "Campo de Besteiros", featured: false},
    {name: "Campo Maior", featured: false},
    {name: "Canas de Santa Maria", featured: false},
    {name: "Canas de Senhorim", featured: false},
    {name: "Caneças", featured: false},
    {name: "Canedo", featured: false},
    {name: "Canelas", featured: false},
    {name: "Caniçal", featured: false},
    {name: "Capelas", featured: false},
    {name: "Caramulo", featured: false},
    {name: "Caranguejeira", featured: false},
    {name: "Carapinheira", featured: false},
    {name: "Caria", featured: false},
    {name: "Carnaxide", featured: false},
    {name: "Carrazeda de Ansiães", featured: false},
    {name: "Carrazedo de Montenegro", featured: false},
    {name: "Carregado", featured: false},
    {name: "Carregal do Sal", featured: false},
    {name: "Carregosa", featured: false},
    {name: "Carvalhos", featured: false},
    {name: "Carvalhosa", featured: false},
    {name: "Carvoeiro", featured: false},
    {name: "Casal de Cambra", featured: false},
    {name: "Castanheira de Pera", featured: false},
    {name: "Castanheira do Ribatejo", featured: false},
    {name: "Castêlo da Maia", featured: false},
    {name: "Castelo de Paiva", featured: false},
    {name: "Castelo de Vide", featured: false},
    {name: "Castro Daire", featured: false},
    {name: "Castro Laboreiro", featured: false},
    {name: "Castro Marim", featured: false},
    {name: "Castro Verde", featured: false},
    {name: "Cavez", featured: false},
    {name: "Caxarias", featured: false},
    {name: "Caxias", featured: false},
    {name: "Cedovim", featured: false},
    {name: "Ceira", featured: false},
    {name: "Cela", featured: false},
    {name: "Celorico da Beira", featured: false},
    {name: "Celorico de Basto", featured: false},
    {name: "Cercal do Alentejo", featured: false},
    {name: "Cernache do Bonjardim", featured: false},
    {name: "Cerva", featured: false},
    {name: "Cesar", featured: false},
    {name: "Cete", featured: false},
    {name: "Chamusca", featured: false},
    {name: "Charneca de Caparica", featured: false},
    {name: "Cinfães", featured: false},
    {name: "Colares", featured: false},
    {name: "Condeixa-a-Nova", featured: false},
    {name: "Constância", featured: false},
    {name: "Corroios", featured: false},
    {name: "Cortegaça", featured: false},
    {name: "Coruche", featured: false},
    {name: "Vila do Corvo", featured: false},
    {name: "Couço", featured: false},
    {name: "Crato", featured: false},
    {name: "Crestuma", featured: false},
    {name: "Cruz Quebrada - Dafundo", featured: false},
    {name: "Cuba", featured: false},
    {name: "Cucujães", featured: false},
    {name: "Cumieira", featured: false},
    {name: "Custóias", featured: false},
    {name: "Darque", featured: false},
    {name: "Eixo", featured: false},
    {name: "Ericeira", featured: false},
    {name: "Ermidas do Sado", featured: false},
    {name: "Ervedosa do Douro", featured: false},
    {name: "Escoural", featured: false},
    {name: "Espinhal", featured: false},
    {name: "Estômbar", featured: false},
    {name: "Estreito de Câmara de Lobos", featured: false},
    {name: "Fajões", featured: false},
    {name: "Famões", featured: false},
    {name: "Fânzeres", featured: false},
    {name: "Fão", featured: false},
    {name: "Favaios", featured: false},
    {name: "Fazendas de Almeirim", featured: false},
    {name: "Febres", featured: false},
    {name: "Fermentelos", featured: false},
    {name: "Fermil de Basto", featured: false},
    {name: "Ferragudo", featured: false},
    {name: "Ferreira do Alentejo", featured: false},
    {name: "Ferreira do Zêzere", featured: false},
    {name: "Ferrel", featured: false},
    {name: "Ferro", featured: false},
    {name: "Figueira de Castelo Rodrigo", featured: false},
    {name: "Figueiró dos Vinhos", featured: false},
    {name: "Fonte Arcada", featured: false},
    {name: "Fontelo", featured: false},
    {name: "Fontes", featured: false},
    {name: "Forjães", featured: false},
    {name: "Fornos de Algodres", featured: false},
    {name: "Forte da Casa", featured: false},
    {name: "Foz do Arelho", featured: false},
    {name: "Frazão", featured: false},
    {name: "Freixianda", featured: false},
    {name: "Freixo de Espada à Cinta", featured: false},
    {name: "Freixo de Numão", featured: false},
    {name: "Fronteira", featured: false},
    {name: "Fuseta", featured: false},
    {name: "Gaeiras", featured: false},
    {name: "Gafanha da Encarnação", featured: false},
    {name: "Gandarela de Basto", featured: false},
    {name: "Gavião", featured: false},
    {name: "Glória do Ribatejo", featured: false},
    {name: "Góis", featured: false},
    {name: "Golegã", featured: false},
    {name: "Gonçalo", featured: false},
    {name: "Grândola", featured: false},
    {name: "Grijó", featured: false},
    {name: "Guia", featured: false},
    {name: "Guifões", featured: false},
    {name: "Idanha-a-Nova", featured: false},
    {name: "Izeda", featured: false},
    {name: "Joane", featured: false},
    {name: "Juncal", featured: false},
    {name: "Lagares da Beira", featured: false},
    {name: "Lajeosa do Dão", featured: false},
    {name: "Lajes", featured: false},
    {name: "Lajes das Flores", featured: false},
    {name: "Lajes do Pico", featured: false},
    {name: "Lalim", featured: false},
    {name: "Lavos", featured: false},
    {name: "Lavra", featured: false},
    {name: "Lavradio", featured: false},
    {name: "Lazarim", featured: false},
    {name: "Leça do Balio", featured: false},
    {name: "Leomil", featured: false},
    {name: "Lever", featured: false},
    {name: "Linda-a-Velha", featured: false},
    {name: "Lobão", featured: false},
    {name: "Longra", featured: false},
    {name: "Lordelo (Guimarães)", featured: false},
    {name: "Lordelo (Vila Real)", featured: false},
    {name: "Loriga", featured: false},
    {name: "Lorvão", featured: false},
    {name: "Loureiro", featured: false},
    {name: "Louriçal", featured: false},
    {name: "Lourinhã", featured: false},
    {name: "Lousã", featured: false},
    {name: "Lousada", featured: false},
    {name: "Luso", featured: false},
    {name: "Luz", featured: false},
    {name: "Luz de Tavira", featured: false},
    {name: "Mação", featured: false},
    {name: "Maceda", featured: false},
    {name: "Maceira", featured: false},
    {name: "Macieira de Cambra", featured: false},
    {name: "Madalena (Açores)", featured: false},
    {name: "Madalena (Porto)", featured: false},
    {name: "Mafra", featured: false},
    {name: "Maiorca", featured: false},
    {name: "Malveira", featured: false},
    {name: "Mamarrosa", featured: false},
    {name: "Manteigas", featured: false},
    {name: "Marialva", featured: false},
    {name: "Marinha das Ondas", featured: false},
    {name: "Marinhais", featured: false},
    {name: "Marvão", featured: false},
    {name: "Melgaço", featured: false},
    {name: "Melres", featured: false},
    {name: "Mértola", featured: false},
    {name: "Mesão Frio", featured: false},
    {name: "Mexilhoeira Grande", featured: false},
    {name: "Minde", featured: false},
    {name: "Mira", featured: false},
    {name: "Mira de Aire", featured: false},
    {name: "Miranda do Corvo", featured: false},
    {name: "Mões", featured: false},
    {name: "Mogadouro", featured: false},
    {name: "Moimenta da Beira", featured: false},
    {name: "Moita", featured: false},
    {name: "Moita dos Ferreiros", featured: false},
    {name: "Monção", featured: false},
    {name: "Moncarapacho", featured: false},
    {name: "Monchique", featured: false},
    {name: "Mondim da Beira", featured: false},
    {name: "Mondim de Basto", featured: false},
    {name: "Monforte", featured: false},
    {name: "Monsanto", featured: false},
    {name: "Montalegre", featured: false},
    {name: "Monte da Caparica", featured: false},
    {name: "Monte Gordo", featured: false},
    {name: "Monte Real", featured: false},
    {name: "Monte Redondo", featured: false},
    {name: "Montelavar", featured: false},
    {name: "Montemor-o-Velho", featured: false},
    {name: "Mora", featured: false},
    {name: "Moreira", featured: false},
    {name: "Moreira de Cónegos", featured: false},
    {name: "Mortágua", featured: false},
    {name: "Moscavide", featured: false},
    {name: "Mourão", featured: false},
    {name: "Mourisca do Vouga", featured: false},
    {name: "Mozelos", featured: false},
    {name: "Murça", featured: false},
    {name: "Murtosa", featured: false},
    {name: "Nazaré", featured: false},
    {name: "Nelas", featured: false},
    {name: "Nespereira", featured: false},
    {name: "Nisa", featured: false},
    {name: "Nogueira da Regedoura", featured: false},
    {name: "Nogueira do Cravo", featured: false},
    {name: "Nordeste", featured: false},
    {name: "Óbidos", featured: false},
    {name: "Odeceixe", featured: false},
    {name: "Odemira", featured: false},
    {name: "Odiáxere", featured: false},
    {name: "Oeiras (Lagos)", featured: false},
    {name: "Oiã", featured: false},
    {name: "Oleiros", featured: false},
    {name: "Olival (Ourém)", featured: false},
    {name: "Olival (Vila Nova de Gaia)", featured: false},
    {name: "Olival Basto", featured: false},
    {name: "Oliveira de Frades", featured: false},
    {name: "Oliveirinha", featured: false},
    {name: "Ourique", featured: false},
    {name: "Paço de Arcos", featured: false},
    {name: "Paço de Sousa", featured: false},
    {name: "Paços de Brandão", featured: false},
    {name: "Paião", featured: false},
    {name: "Palhaça", featured: false},
    {name: "Palmela", featured: false},
    {name: "Pampilhosa", featured: false},
    {name: "Pampilhosa da Serra", featured: false},
    {name: "Paranhos da Beira", featured: false},
    {name: "Parchal", featured: false},
    {name: "Pardilhó", featured: false},
    {name: "Parede", featured: false},
    {name: "Paredes de Coura", featured: false},
    {name: "Pataias", featured: false},
    {name: "Paul", featured: false},
    {name: "Pedras Salgadas", featured: false},
    {name: "Pedrógão Grande", featured: false},
    {name: "Pedroso", featured: false},
    {name: "Penacova", featured: false},
    {name: "Penalva do Castelo", featured: false},
    {name: "Penamacor", featured: false},
    {name: "Penedono", featured: false},
    {name: "Penela", featured: false},
    {name: "Pêra", featured: false},
    {name: "Perafita", featured: false},
    {name: "Pereira", featured: false},
    {name: "Pero Pinheiro", featured: false},
    {name: "Perosinho", featured: false},
    {name: "Pevidém", featured: false},
    {name: "Pias", featured: false},
    {name: "Pico de Regalados", featured: false},
    {name: "Pinhal Novo", featured: false},
    {name: "Pinhão", featured: false},
    {name: "Pinheiro da Bemposta", featured: false},
    {name: "Ponta do Sol", featured: false},
    {name: "Ponte", featured: false},
    {name: "Ponte da Barca", featured: false},
    {name: "Ponte de Lima", featured: false},
    {name: "Pontével", featured: false},
    {name: "Pontinha", featured: false},
    {name: "Porches", featured: false},
    {name: "Portel", featured: false},
    {name: "Porto da Cruz", featured: false},
    {name: "Porto de Mós", featured: false},
    {name: "Porto Judeu", featured: false},
    {name: "Porto Moniz", featured: false},
    {name: "Porto Salvo", featured: false},
    {name: "Póvoa de Lanhoso", featured: false},
    {name: "Póvoa de Santo Adrião", featured: false},
    {name: "Povoação", featured: false},
    {name: "Vila da Praia", featured: false},
    {name: "Praia de Mira", featured: false},
    {name: "Prior Velho", featured: false},
    {name: "Proença-a-Nova", featured: false},
    {name: "Queijas", featured: false},
    {name: "Quinta do Conde", featured: false},
    {name: "Rabo de Peixe", featured: false},
    {name: "Raiva", featured: false},
    {name: "Ramada", featured: false},
    {name: "Rebordões", featured: false},
    {name: "Recarei", featured: false},
    {name: "Redondo", featured: false},
    {name: "Resende", featured: false},
    {name: "Riachos", featured: false},
    {name: "Riba de Ave", featured: false},
    {name: "Ribamar", featured: false},
    {name: "Ribeira Brava", featured: false},
    {name: "Ribeira de Pena", featured: false},
    {name: "Ribeirão", featured: false},
    {name: "Rio de Moinhos", featured: false},
    {name: "Rio de Mouro", featured: false},
    {name: "Rio Meão", featured: false},
    {name: "Ronfe", featured: false},
    {name: "Roriz", featured: false},
    {name: "Rossas", featured: false},
    {name: "Sabrosa", featured: false},
    {name: "Vila de Sagres", featured: false},
    {name: "Salir", featured: false},
    {name: "Salreu", featured: false},
    {name: "Salto", featured: false},
    {name: "Salvaterra de Magos", featured: false},
    {name: "Salzedas", featured: false},
    {name: "Samouco", featured: false},
    {name: "Sandim", featured: false},
    {name: "Sanfins do Douro", featured: false},
    {name: "Sangalhos", featured: false},
    {name: "Santa Catarina", featured: false},
    {name: "Santa Catarina da Serra", featured: false},
    {name: "Santa Cruz da Graciosa", featured: false},
    {name: "Santa Cruz da Trapa", featured: false},
    {name: "Santa Cruz das Flores", featured: false},
    {name: "Santa Eulália", featured: false},
    {name: "Santa Iria de Azoia", featured: false},
    {name: "Santa Luzia", featured: false},
    {name: "Santa Maria de Lamas", featured: false},
    {name: "Santa Maria de Sardoura", featured: false},
    {name: "Santa Marinha", featured: false},
    {name: "Santa Marinha do Zêzere", featured: false},
    {name: "Santa Marta de Penaguião", featured: false},
    {name: "Santar", featured: false},
    {name: "Santo André", featured: false},
    {name: "Santo António dos Cavaleiros", featured: false},
    {name: "Santo Estêvão", featured: false},
    {name: "São Bartolomeu de Messines", featured: false},
    {name: "São Brás de Alportel", featured: false},
    {name: "São Cosmado", featured: false},
    {name: "São Félix da Marinha", featured: false},
    {name: "São João da Pesqueira", featured: false},
    {name: "São João da Talha", featured: false},
    {name: "São João de Areias", featured: false},
    {name: "São João de Ovar", featured: false},
    {name: "São João de Tarouca", featured: false},
    {name: "São João de Ver", featured: false},
    {name: "São João do Campo", featured: false},
    {name: "São João do Monte", featured: false},
    {name: "São Mamede", featured: false},
    {name: "São Manços", featured: false},
    {name: "São Martinho de Anta", featured: false},
    {name: "São Martinho de Mouros", featured: false},
    {name: "São Martinho do Campo", featured: false},
    {name: "São Martinho do Porto", featured: false},
    {name: "São Miguel de Machede", featured: false},
    {name: "São Miguel de Souto", featured: false},
    {name: "São Paio de Oleiros", featured: false},
    {name: "São Pedro", featured: false},
    {name: "São Pedro da Cova", featured: false},
    {name: "São Pedro de Alva", featured: false},
    {name: "São Pedro de Castelões", featured: false},
    {name: "São Pedro de Rates", featured: false},
    {name: "São Romão", featured: false},
    {name: "São Romão de Arões", featured: false},
    {name: "São Roque do Pico", featured: false},
    {name: "São Teotónio", featured: false},
    {name: "São Tomé de Negrelos", featured: false},
    {name: "São Torcato", featured: false},
    {name: "São Vicente", featured: false},
    {name: "Sardoal", featured: false},
    {name: "Sátão", featured: false},
    {name: "Seixo da Beira", featured: false},
    {name: "Sendim (Miranda do Douro)", featured: false},
    {name: "Sendim (Tabuaço)", featured: false},
    {name: "Senhora Aparecida", featured: false},
    {name: "Sernancelhe", featured: false},
    {name: "Serra d'El-Rei", featured: false},
    {name: "Sertã", featured: false},
    {name: "Serzedelo", featured: false},
    {name: "Serzedo", featured: false},
    {name: "Sesimbra", featured: false},
    {name: "Sever do Vouga", featured: false},
    {name: "Silgueiros", featured: false},
    {name: "Silvalde", featured: false},
    {name: "Silvares", featured: false},
    {name: "Soajo", featured: false},
    {name: "Soalheira", featured: false},
    {name: "Sobrado", featured: false},
    {name: "Sobral de Monte Agraço", featured: false},
    {name: "Sobralinho", featured: false},
    {name: "Sobreda", featured: false},
    {name: "Sobreira", featured: false},
    {name: "Sobrosa", featured: false},
    {name: "Sosa", featured: false},
    {name: "Soure", featured: false},
    {name: "Sousel", featured: false},
    {name: "Souselas", featured: false},
    {name: "Souselo", featured: false},
    {name: "Souto", featured: false},
    {name: "Tábua", featured: false},
    {name: "Tabuaço", featured: false},
    {name: "Tavarede", featured: false},
    {name: "Taveiro", featured: false},
    {name: "Teixoso", featured: false},
    {name: "Tentúgal", featured: false},
    {name: "Termas do Gerês", featured: false},
    {name: "Terras de Bouro", featured: false},
    {name: "Terrugem", featured: false},
    {name: "Tocha", featured: false},
    {name: "Torre de Dona Chama", featured: false},
    {name: "Torre de Moncorvo", featured: false},
    {name: "Torredeita", featured: false},
    {name: "Torreira", featured: false},
    {name: "Tortosendo", featured: false},
    {name: "Trafaria", featured: false},
    {name: "Tramagal", featured: false},
    {name: "Tremês", featured: false},
    {name: "Trevões", featured: false},
    {name: "Troviscal", featured: false},
    {name: "Turcifal", featured: false},
    {name: "Turquel", featured: false},
    {name: "Unhais da Serra", featured: false},
    {name: "Vagos", featured: false},
    {name: "Valadares", featured: false},
    {name: "Valado dos Frades", featured: false},
    {name: "Valdigem", featured: false},
    {name: "Vale de Santarém", featured: false},
    {name: "Válega", featured: false},
    {name: "Valongo do Vouga", featured: false},
    {name: "Velas", featured: false},
    {name: "Verride", featured: false},
    {name: "Vialonga", featured: false},
    {name: "Viana do Alentejo", featured: false},
    {name: "Vidago", featured: false},
    {name: "Vidigueira", featured: false},
    {name: "Vieira de Leiria", featured: false},
    {name: "Vieira do Minho", featured: false},
    {name: "Vila Chã de Ourique", featured: false},
    {name: "Vila Chã de São Roque", featured: false},
    {name: "Vila Cova à Coelheira", featured: false},
    {name: "Vila da Marmeleira", featured: false},
    {name: "Vila das Aves", featured: false},
    {name: "Vila de Alpendurada", featured: false},
    {name: "Vila de Prado", featured: false},
    {name: "Vila de Rei", featured: false},
    {name: "Vila de São Sebastião", featured: false},
    {name: "Vila do Bispo", featured: false},
    {name: "Vila do Carvalho", featured: false},
    {name: "Vila do Coronado", featured: false},
    {name: "Vila do Porto", featured: false},
    {name: "Vila do Topo", featured: false},
    {name: "Vila Flor", featured: false},
    {name: "Vila Franca das Naves", featured: false},
    {name: "Vila Franca do Campo", featured: false},
    {name: "Vila Meã", featured: false},
    {name: "Vila Nova da Barquinha", featured: false},
    {name: "Vila Nova da Rainha", featured: false},
    {name: "Vila Nova de Anha", featured: false},
    {name: "Vila Nova de Cacela", featured: false},
    {name: "Vila Nova de Cerveira", featured: false},
    {name: "Vila Nova de Milfontes", featured: false},
    {name: "Vila Nova de Oliveirinha", featured: false},
    {name: "Vila Nova de Paiva", featured: false},
    {name: "Vila Nova de Poiares", featured: false},
    {name: "Vila Nova de São Bento", featured: false},
    {name: "Vila Nova de Tazem", featured: false},
    {name: "Vila Pouca de Aguiar", featured: false},
    {name: "Vila Praia de Âncora", featured: false},
    {name: "Vila Velha de Ródão", featured: false},
    {name: "Vila Verde", featured: false},
    {name: "Vila Viçosa", featured: false},
    {name: "Vilar de Maçada", featured: false},
    {name: "Vilar dos Prazeres", featured: false},
    {name: "Vilar Formoso", featured: false},
    {name: "Vilarandelo", featured: false},
    {name: "Vilarinho", featured: false},
    {name: "Vilela", featured: false},
    {name: "Vimioso", featured: false},
    {name: "Vinhais", featured: false},
    {name: "Vouzela", featured: false}
];


MongoClient.connect(URL, function(err, db) {
  if (err) throw err;
  var dbo = db.db(DB_NAME);


  dbo.collection("cities").insertMany(cities, function(err, res) {
    if (err) throw err;
    console.log("Number of documents inserted: " + res.insertedCount);
    db.close();
  });
});



